import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import '../globals.css';
import { cn } from '@/lib/utils';
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar';
import { AppSidebar } from '@/components/app-sidebar';
import NavDash from '@/components/dashboard/NavDash';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' className={cn('h-full', 'antialiased', 'font-sans', inter.variable)}>
      <body className='w-full'>
        <SidebarProvider>
          <AppSidebar />
          <main className='w-full overflow-hidden'>
            <NavDash />
            <div>{children}</div>
          </main>
        </SidebarProvider>
      </body>
    </html>
  );
}
